In [1]:
import numpy as np 
import pandas as pd
import nicaviz
import seaborn as sns

In [2]:
postings = pd.read_csv(r"D:\Project\job-market-intelligence\raw_data\postings.csv")
postings

In [12]:
postings

,job_id,company_name,title,description,max_salary,pay_period,location,company_id,views,med_salary,...,skills_desc,listed_time,posting_domain,sponsored,work_type,currency,compensation_type,normalized_salary,zip_code,fips
0,921716,Corcoran Sawyer Smith,Marketing Coordinator,Job descriptionA leading real estate firm in N...,20.0,HOURLY,"Princeton, NJ",2774458.0,20.0,NaN,...,Requirements: \n\nWe are seeking a College or ...,1.713398e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,38480.0,8540.0,34021.0
1,1829192,NaN,Mental Health Therapist/Counselor,"At Aspen Therapy and Wellness , we are committ...",50.0,HOURLY,"Fort Collins, CO",NaN,1.0,NaN,...,NaN,1.712858e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,83200.0,80521.0,8069.0
2,10998357,The National Exemplar,Assitant Restaurant Manager,The National Exemplar is accepting application...,65000.0,YEARLY,"Cincinnati, OH",64896719.0,8.0,NaN,...,We are currently accepting resumes for FOH - A...,1.713278e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,55000.0,45202.0,39061.0
3,23221523,"Abrams Fensterman, LLP",Senior Elder Law / Trusts and Estates Associat...,Senior Associate Attorney - Elder Law / Trusts...,175000.0,YEARLY,"New Hyde Park, NY",766262.0,16.0,NaN,...,This position requires a baseline understandin...,1.712896e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,157500.0,11040.0,36059.0
4,35982263,NaN,Service Technician,Looking for HVAC service tech with experience ...,80000.0,YEARLY,"Burlington, IA",NaN,3.0,NaN,...,NaN,1.713452e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,70000.0,52601.0,19057.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
123844,3906267117,Lozano Smith,Title IX/Investigations Attorney,Our Walnut Creek office is currently seeking a...,195000.0,YEARLY,"Walnut Creek, CA",56120.0,1.0,NaN,...,NaN,1.713571e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,157500.0,94595.0,6013.0
123845,3906267126,Pinterest,"Staff Software Engineer, ML Serving Platform",About Pinterest:\n\nMillions of people across ...,NaN,NaN,United States,1124131.0,3.0,NaN,...,NaN,1.713572e+12,www.pinterestcareers.com,0,FULL_TIME,NaN,NaN,NaN,NaN,NaN
123846,3906267131,EPS Learning,"Account Executive, Oregon/Washington",Company Overview\n\nEPS Learning is a leading ...,NaN,NaN,"Spokane, WA",90552133.0,3.0,NaN,...,NaN,1.713572e+12,epsoperations.bamboohr.com,0,FULL_TIME,NaN,NaN,NaN,99201.0,53063.0
123847,3906267195,Trelleborg Applied Technologies,Business Development Manager,The Business Development Manager is a 'hunter'...,NaN,NaN,"Texas, United States",2793699.0,4.0,NaN,...,NaN,1.713573e+12,NaN,0,FULL_TIME,NaN,NaN,NaN,NaN,NaN
123848,3906267224,Solugenix,Marketing Social Media Specialist,Marketing Social Media Specialist - $70k – $75...,75000.0,YEARLY,"San Juan Capistrano, CA",43325.0,2.0,NaN,...,NaN,1.713573e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,72500.0,92675.0,6059.0

In [7]:
pd.unique(postings[['currency','work_type']].values.ravel())

array(['USD', 'FULL_TIME', 'INTERNSHIP', 'CONTRACT', nan, 'PART_TIME',
       'TEMPORARY', 'VOLUNTEER', 'OTHER', 'CAD', 'BBD', 'EUR', 'AUD',
       'GBP'], dtype=object)

In [25]:
postings.groupby("currency").agg({
    "med_salary": ["count", "mean"],
    "max_salary": ["count", "mean"],
    "min_salary": ["count", "mean"],
    "normalized_salary": ["count", "mean"]
}).reset_index()

  currency med_salary               max_salary                min_salary  \
                count          mean      count           mean      count
0      AUD          0           NaN          2  114591.000000          2
1      BBD          0           NaN          2   68750.000000          2
2      CAD          0           NaN          3   87086.666667          3
3      EUR          0           NaN          6   30445.333333          6
4      GBP          0           NaN          2      12.500000          2
5      USD       6280  22015.619876      29778   91958.513136      29778

                normalized_salary
           mean             count           mean
0  77248.000000                 2   95919.500000
1  48750.000000                 2   58750.000000
2  63818.333333                 3  115300.000000
3  29278.666667                 6   29862.000000
4     12.500000                 2   26000.000000
5  64922.752690             36058  205387.869246

In [48]:
exchange_rates = {
    "USD": 1.0,
    "EUR": 1.1,
    "GBP": 1.25,
    "CAD": 0.75,
    "AUD": 0.65,
    "BBD": 0.5
}
rates = postings["currency"].map(exchange_rates)
postings[["med_salary", "max_salary", "min_salary", "normalized_salary"]] =postings[["med_salary", "max_salary", "min_salary", "normalized_salary"]].multiply(rates, axis=0)
postings.drop(columns="currency",inplace=True)

In [29]:
postings.info()

<class 'pandas.DataFrame'>
RangeIndex: 123849 entries, 0 to 123848
Data columns (total 27 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   job_id                      123849 non-null  int64
 1   company_name                122130 non-null  str
 2   title                       123849 non-null  str
 3   description                 123842 non-null  str
 4   max_salary                  29793 non-null   float64
 5   pay_period                  36073 non-null   str
 6   location                    123849 non-null  str
 7   company_id                  122132 non-null  float64
 8   views                       122160 non-null  float64
 9   med_salary                  6280 non-null    float64
 10  min_salary                  29793 non-null   float64
 11  formatted_work_type         123849 non-null  str
 12  applies                     23320 non-null   float64
 13  original_listed_time        123849 non-null  datetime64[ms]
 14  remote_allowed              15246 non-null   float64
 15  application_url             87184 non-null   str
 16  application_type            123849 non-null  str
 17  expiry                      123849 non-null  float64
 18  closed_time                 1073 non-null    datetime64[ms]
 19  formatted_experience_level  94440 non-null   str
 20  listed_time                 123849 non-null  datetime64[ms]
 21  posting_domain              83881 non-null   str
 22  sponsored                   123849 non-null  bool
 23  work_type                   123849 non-null  str
 24  currency                    36073 non-null   str
 25  compensation_type           36073 non-null   str
 26  normalized_salary           36073 non-null   float64
dtypes: bool(1), datetime64[ms](3), float64(9), int64(1), str(13)
memory usage: 24.7 MB

In [30]:
postings.select_dtypes(include =['float64','int64']).describe()

,job_id,max_salary,company_id,views,med_salary,min_salary,applies,remote_allowed,expiry,normalized_salary
count,1.238490e+05,2.979300e+04,1.221320e+05,122160.000000,6280.000000,2.979300e+04,23320.000000,15246.0,1.238490e+05,3.607300e+04
mean,3.896402e+09,9.193284e+04,1.220401e+07,14.618247,22015.619876,6.490638e+04,10.591981,1.0,1.716213e+12,2.053220e+05
std,8.404355e+07,7.011101e+05,2.554143e+07,85.903598,52255.873846,4.959738e+05,29.047395,0.0,2.321394e+09,5.097627e+06
min,9.217160e+05,1.000000e+00,1.009000e+03,1.000000,0.000000,1.000000e+00,1.000000,1.0,1.712903e+12,0.000000e+00
25%,3.894587e+09,4.824000e+01,1.435200e+04,3.000000,18.940000,3.700000e+01,1.000000,1.0,1.715481e+12,5.200000e+04
50%,3.901998e+09,8.000000e+04,2.269650e+05,4.000000,25.500000,6.000000e+04,3.000000,1.0,1.716042e+12,8.149100e+04
75%,3.904707e+09,1.400000e+05,8.047188e+06,8.000000,2510.500000,1.000000e+05,8.000000,1.0,1.716088e+12,1.250000e+05
max,3.906267e+09,1.200000e+08,1.034730e+08,9975.000000,750000.000000,8.500000e+07,967.000000,1.0,1.729125e+12,5.356000e+08

In [31]:
display(postings.nica.categorical_describe())

Dataframe Dimension: 123849 Rows, 27 Columns

,Unique,Missing,dtype,ValCount 1,Occ,ValCount 2,Occ,ValCount 3,Occ,ValCount 4,Occ,ValCount 5,Occ
Column,,,,,,,,,,,,,
job_id,123849,0,int64,921716,1,1829192,1.0,10998357,1.0,23221523,1.0,35982263,1.0
company_name,24428,1719,str,Liberty Healthcare and Rehabilitation Services,1108,The Job Network,1003.0,J. Galt,604.0,TEKsystems,529.0,"Lowe's Companies, Inc.",527.0
title,72521,0,str,Sales Manager,673,Customer Service Representative,373.0,Project Manager,354.0,Administrative Assistant,254.0,Senior Accountant,238.0
description,107827,7,str,Position Summary: Our Sales Manager has managi...,474,Store Family Dollar\n\nGeneral Summary:\n\nWor...,167.0,"JOB GOAL \n Plan, organize and implement an ap...",127.0,Store Dollar Tree\n\nWork where you love to sh...,117.0,Claire's - A Career that's always in style\n\n...,105.0
max_salary,5326,94056,float64,150000.0,648,100000.0,635.0,120000.0,610.0,90000.0,541.0,85000.0,534.0
pay_period,5,87776,str,YEARLY,20628,HOURLY,14741.0,MONTHLY,518.0,WEEKLY,177.0,BIWEEKLY,9.0
location,8526,0,str,United States,8125,"New York, NY",2756.0,"Chicago, IL",1834.0,"Houston, TX",1762.0,"Dallas, TX",1383.0
company_id,24474,1717,float64,53345529.0,1108,167757.0,1003.0,73013724.0,604.0,2152.0,529.0,4128.0,527.0
views,684,1689,float64,4.0,28323,3.0,16960.0,5.0,14513.0,2.0,14417.0,6.0,7834.0
med_salary,1417,117569,float64,20.0,268,18.0,243.0,15.0,177.0,17.0,169.0,16.0,158.0
min_salary,4619,94056,float64,100000.0,873,80000.0,841.0,90000.0,766.0,70000.0,752.0,60000.0,676.0
formatted_work_type,7,0,str,Full-time,98814,Contract,12117.0,Part-time,9696.0,Temporary,1190.0,Internship,983.0
applies,274,100529,float64,1.0,7830,2.0,3351.0,3.0,2053.0,4.0,1395.0,5.0,1108.0
original_listed_time,65036,0,datetime64[ms],2024-04-18 00:00:00,6788,2024-04-17 00:00:00,3979.0,2024-04-19 00:00:00,3373.0,2024-04-05 00:00:00,1975.0,2024-04-11 00:00:00,1966.0
remote_allowed,1,108603,float64,1.0,15246,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
application_url,84800,36665,str,https://app.dataannotation.tech/worker_signup?...,205,https://revature.com/jobs/entry-level-automoti...,67.0,https://app.dataannotation.tech/worker_signup?...,60.0,https://www.english1.com/apply-now/?utm_source...,44.0,https://optimabiosupply.com/job-opening-data-e...,43.0
application_type,4,0,str,OffsiteApply,84607,ComplexOnsiteApply,31049.0,SimpleOnsiteApply,8192.0,UnknownApply,1.0,NaN,NaN
expiry,54851,0,float64,1714966714000.0,123,1716110539000.0,96.0,1716110364000.0,94.0,1716085196000.0,91.0,1715869799000.0,89.0
closed_time,698,122776,datetime64[ms],2024-04-09 13:34:50,15,2024-04-09 13:36:15,15.0,2024-04-09 13:37:20,14.0,2024-04-09 13:37:19,14.0,2024-04-09 13:36:18,11.0
formatted_experience_level,6,29409,str,Mid-Senior level,41489,Entry level,36708.0,Associate,9826.0,Director,3746.0,Internship,1449.0
listed_time,53231,0,datetime64[ms],2024-04-06 03:38:34,123,2024-04-19 09:22:19,96.0,2024-04-19 09:19:24,94.0,2024-04-19 02:19:56,91.0,2024-04-16 14:29:59,90.0
posting_domain,4443,39968,str,www.click2apply.net,3811,click.appcast.io,2255.0,jsv3.recruitics.com,1921.0,jobs.smartrecruiters.com,1557.0,boards.greenhouse.io,1493.0
sponsored,1,0,bool,False,123849,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
work_type,7,0,str,FULL_TIME,98814,CONTRACT,12117.0,PART_TIME,9696.0,TEMPORARY,1190.0,INTERNSHIP,983.0
currency,6,87776,str,USD,36058,EUR,6.0,CAD,3.0,BBD,2.0,AUD,2.0
compensation_type,1,87776,str,BASE_SALARY,36073,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
normalized_salary,7303,87776,float64,41600.0,416,100000.0,410.0,75000.0,393.0,80000.0,388.0,70000.0,387.0

In [51]:
f = (postings.isna().mean(axis=1)*26).sort_values(ascending=False)
f

17123     15.0
91061     15.0
101192    15.0
112727    15.0
55513     15.0
          ...
42565      2.0
42576      2.0
111269     2.0
42435      2.0
26498      2.0
Length: 123849, dtype: float64

In [49]:
(postings.isna().mean()*100).sort_values(ascending = False)

closed_time                   99.133622
med_salary                    94.929309
remote_allowed                87.689848
applies                       81.170619
min_salary                    75.944093
max_salary                    75.944093
pay_period                    70.873402
normalized_salary             70.873402
compensation_type             70.873402
posting_domain                32.271556
application_url               29.604599
formatted_experience_level    23.745852
company_name                   1.387981
company_id                     1.386366
views                          1.363757
description                    0.005652
job_id                         0.000000
title                          0.000000
location                       0.000000
application_type               0.000000
formatted_work_type            0.000000
original_listed_time           0.000000
expiry                         0.000000
listed_time                    0.000000
work_type                      0.000000
sponsored                      0.000000
dtype: float64

In [13]:
time_multiplier = {
    'HOURLY': 40*52,
    'WEEKLY': 52,
    'BIWEEKLY': 26,
    'MONTHLY': 12,
    'YEARLY': 1
}

postings['normalized_salary'] = (
    postings[['min_salary', 'max_salary']].mean(axis=1).fillna(postings['med_salary'])
)

postings['normalized_salary'] = (
    postings['normalized_salary'] * postings['pay_period'].map(time_multiplier)
)

postings[['original_listed_time', 'closed_time', 'listed_time']] = (
    postings[['original_listed_time', 'closed_time', 'listed_time']].apply(pd.to_datetime, unit='ms')
)

postings['sponsored'] = postings['sponsored'].eq(1)

In [44]:
(postings.isna().mean()*100).sort_values(ascending = False)

closed_time                   99.133622
med_salary                    94.929309
remote_allowed                87.689848
applies                       81.170619
max_salary                    75.944093
min_salary                    75.944093
pay_period                    70.873402
compensation_type             70.873402
normalized_salary             70.873402
currency                      70.873402
posting_domain                32.271556
application_url               29.604599
formatted_experience_level    23.745852
company_name                   1.387981
company_id                     1.386366
views                          1.363757
description                    0.005652
job_id                         0.000000
title                          0.000000
location                       0.000000
application_type               0.000000
formatted_work_type            0.000000
original_listed_time           0.000000
expiry                         0.000000
listed_time                    0.000000
sponsored                      0.000000
work_type                      0.000000
dtype: float64

In [64]:
postings = postings.drop(columns=["skills_desc","zip_code","fips","job_posting_url","application_url","closed_time","med_salary"])

In [52]:
def row_quality_pipeline(df,weights=None,drop_threshold=0.85,default_weight=1,low_q=0.2,high_q=0.8):
    
    df = df.copy()
    missing_rate = df.isna().mean()

    selected_features = missing_rate[missing_rate < drop_threshold].index.tolist()

    if weights is None:
        weights = {}

    adjusted_weights = {}

    for col in selected_features:
        base_w = weights.get(col, default_weight)
        adjusted_w = base_w * (1 - missing_rate[col])
        adjusted_weights[col] = adjusted_w

    def compute_score(row):
        total_weight = 0
        score = 0
        
        for col, w in adjusted_weights.items():
            total_weight += w
            if pd.notna(row[col]):
                score += w
        
        return score / total_weight if total_weight > 0 else 0

    df["row_score"] = df.apply(compute_score, axis=1)

    low = df["row_score"].quantile(low_q)
    high = df["row_score"].quantile(high_q)

    def decision(score):
        if score < low:
            return "drop"
        elif score < high:
            return "review"
        else:
            return "keep"

    df["decision"] = df["row_score"].apply(decision)

    total_rows = len(df)
    counts = df["decision"].value_counts()

    summary = {
        "total_rows": total_rows,
        "keep_count": counts.get("keep", 0),
        "review_count": counts.get("review", 0),
        "drop_count": counts.get("drop", 0),
        "keep_pct": counts.get("keep", 0) / total_rows,
        "review_pct": counts.get("review", 0) / total_rows,
        "drop_pct": counts.get("drop", 0) / total_rows,
    }

    return df, summary

In [61]:
weights = {
    "title": 10,
    "description": 10,
    "location": 9,
    "company_name": 8,
    "formatted_experience_level": 6,
    "work_type": 6,
    "min_salary": 5,
    "max_salary": 5,
    "normalized_salary": 6,
    "views": 2,
    "applies": 3,
}

df_processed, summary = row_quality_pipeline(df,weights=weights,drop_threshold=0.85)

print(summary)

{'total_rows': 123849, 'keep_count': np.int64(24838), 'review_count': np.int64(74244), 'drop_count': np.int64(24767), 'keep_pct': np.float64(0.2005506705746514), 'review_pct': np.float64(0.599471937601434), 'drop_pct': np.float64(0.1999773918239146)}

In [62]:
postings = df_processed

In [65]:
(postings.isna().mean()*100).sort_values(ascending = False)

remote_allowed                87.689848
applies                       81.170619
min_salary                    75.944093
max_salary                    75.944093
pay_period                    70.873402
compensation_type             70.873402
currency                      70.873402
normalized_salary             70.873402
posting_domain                32.271556
formatted_experience_level    23.745852
company_name                   1.387981
company_id                     1.386366
views                          1.363757
description                    0.005652
location                       0.000000
title                          0.000000
job_id                         0.000000
formatted_work_type            0.000000
listed_time                    0.000000
expiry                         0.000000
application_type               0.000000
original_listed_time           0.000000
work_type                      0.000000
sponsored                      0.000000
row_score                      0.000000
decision                       0.000000
dtype: float64